src/Entity/Event.php
<?php

namespace App\Entity;

use App\Repository\EventRepository;
use DateTime;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: EventRepository::class)]
class Event
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank]
    private ?string $name = null;

    #[ORM\Column(type: Types::TEXT)]
    #[Assert\NotBlank, Assert\Length(min: 2)]
    private ?string $description = null;

    #[ORM\Column(nullable: true)]
    #[Assert\Range(min: 10000, max: 50000)]
    private ?int $price = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $created_at = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    #[Assert\NotBlank, Assert\GreaterThan('today 14:00')]
    private ?\DateTimeInterface $released_at = null;
    
    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    #[Assert\NotBlank, Assert\GreaterThan(propertyPath: 'released_at')]
    private ?\DateTimeInterface $finished_at = null;
    
    #[ORM\Column(length: 255, nullable: true)]
    private ?string $image = null;

    public function __construct()
    {
        $this->created_at = new DateTime();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(?int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getReleasedAt(): ?\DateTimeInterface
    {
        return $this->released_at;
    }

    public function setReleasedAt(\DateTimeInterface $released_at): self
    {
        $this->released_at = $released_at;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getFinishedAt(): ?\DateTimeInterface
    {
        return $this->finished_at;
    }

    public function setFinishedAt(\DateTimeInterface $finished_at): self
    {
        $this->finished_at = $finished_at;

        return $this;
    }
}

src/Form/EventType.php
<?php

namespace App\Form;

use App\Entity\Event;
use DateTime;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EventType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name', options: [
                'label' => 'Nom'
            ])
            ->add('description')
            ->add('price', options: [
                'label' => 'Prix'
            ])
            ->add('released_at', options: [
                'label' => 'Commence le',
                'years' => range(2022, 2032)
            ])
            ->add('finished_at', options: [
                'label' => 'Termine le',
                'years' => range(2022, 2032)
            ])
            ->add('image')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Event::class,
        ]);
    }
}

src/Controller/EventController.php
<?php

namespace App\Controller;

use App\Entity\Event;
use App\Form\EventType;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\Mime\Email;
use Symfony\Component\Routing\Annotation\Route;

class EventController extends AbstractController
{
    public $doctrine;
    public $entityManager;
    public $mailer;

    public function __construct(ManagerRegistry $doctrine, MailerInterface $mailer)
    {
        $this->doctrine = $doctrine;
        $this->entityManager = $doctrine->getManager();
        $this->mailer = $mailer;
    }

    #[Route('/home', name: 'home')]
    public function home(): Response
    {
        $title = 'Bienvenue sur Event Time';

        return $this->render('event/index.html.twig', [
            'title' => $title,
        ]);
    }

    #[Route('/list', name: 'list')]
    public function list(): Response
    {
        $events = $this->doctrine->getRepository(Event::class)->findBy([], ['finished_at' => 'DESC']);

        return $this->render('event/list.html.twig', [
            'events' => $events,
        ]);
    }

    #[Route('/create', name: 'create')]
    public function create(Request $request): Response
    {
        $event = new Event();
        $form = $this->createForm(EventType::class, $event);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->entityManager->persist($event);
            $this->entityManager->flush();

            $this->addFlash('success', 'L\'événement '.$event->getName().' a été créé !');
            return $this->redirectToRoute('list');
        }

        return $this->render('event/create.html.twig', [
            'form' => $form->createView()
        ]);
    }

    #[Route('/show/{id}', name: 'show')]
    public function show(Event $event): Response
    {
        return $this->render('event/show.html.twig', [
            'event' => $event
        ]);
    }

    #[Route('/join/{id}', name: 'join')]
    public function join(Event $event): Response
    {
        $email = (new Email())
            ->from('test@test.fr')
            ->to('admin@test.fr')
            ->subject('Rejoindre l\'événement')
            ->html('<p>Evenement: '.$event->getName().'</p>')
        ;

        $this->mailer->send($email);

        return $this->redirectToRoute('home');
    }
}

templates/Form/form.html.twig
{% use 'tailwind_2_layout.html.twig' %}

{%- block widget_attributes -%}
    {%- set widget_class = widget_class|default('mt-1 w-full rounded-lg border-gray-300') -%}
    {{- parent() -}}
{%- endblock widget_attributes -%}

{%- block form_label -%}
    {% set label_class = label_class|default('block text-gray-800 text-sm font-semibold') %}
    {{- parent() -}}
{%- endblock form_label -%}

{%- block form_errors -%}
    {% set error_item_class = error_item_class|default('text-red-700 text-sm') %}
    {{- parent() -}}
{%- endblock form_errors -%}

{% block datetime_widget -%}
    {%- set attr = attr|merge({ class: attr.class|default('flex w-full items-center space-x-4') }) -%}
    {{- parent() -}}
{%- endblock datetime_widget %}

{% block date_widget -%}
    {%- set attr = attr|merge({ class: attr.class|default('flex w-full items-center space-x-4') }) -%}
    {{- parent() -}}
{%- endblock date_widget %}

{% block time_widget -%}
    {%- set attr = attr|merge({ class: attr.class|default('flex w-full items-center space-x-4') }) -%}
    {{- parent() -}}
{%- endblock time_widget %}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Event time{% endblock %}</title>
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">
        <script src="https://cdn.tailwindcss.com?plugins=forms,typography,aspect-ratio,line-clamp"></script>
        {% block stylesheets %}
            {{ encore_entry_link_tags('app') }}
        {% endblock %}

        {% block javascripts %}
            {{ encore_entry_script_tags('app') }}
        {% endblock %}
    </head>

    <body>
        <header class="bg-slate-100 h-[10vh] px-10 mx-auto mb-6 border-b flex justify-between items-center">
            <h1 class="text-2xl text-black font-semibold">Event Time</h1>
            <ul class="flex gap-8 text-lg">
                <li><a class="pb-1 border-black hover:border-b-2 hover:border-b" href="{{ path('home') }}">Accueil</a></li>
                <li><a class="pb-1 border-black hover:border-b-2 hover:border-b" href="{{ path('list') }}">Evénements</a></li>
                <li><a class="pb-1 border-black hover:border-b-2 hover:border-b" href="{{ path('create') }}">Créer un événement</a></li>
                <li><a class="pb-1 border-black hover:border-b-2 hover:border-b" href="#">Hello</a></li>
            </ul>
        </header>

        {% block body %}{% endblock %}

        <footer class="bg-slate-100 h-[10vh] px-10 mx-auto mt-6 border-t flex justify-between items-center">
            <p class="text-center w-full">Tous droits réservés</p>
        </footer>
    </body>
</html>

templates/event/create.html.twig
{% extends "base.html.twig" %}

{% block title %}{{ parent() }} - Ajouter{% endblock %}

{% block body %}

    <h2 class="text-center text-2xl font-semibold my-8 text-black">Créer un événement</h2>

    <section class="max-w-[800px] mx-auto">
        {{ form_start(form) }}
            {{ form_widget(form) }}
            <div class="flex justify-center">
                <button class="bg-blue-500 text-white px-2 py-1 duration-500 rounded hover:bg-blue-600">Créer</button>
            </div>
        {{ form_end(form) }}
    </section>
    
{% endblock %}

templates/event/index.html.twig
{% extends 'base.html.twig' %}

{% block title %} {{ parent() }} - Accueil{% endblock %}

{% block body %}

    <h2 class="text-center text-2xl font-semibold my-8 text-black">{{ title }}</h2>

    <section class="w-[300px] mx-auto flex justify-center">
        <a class="inline-block bg-slate-500 text-white text-center px-2 py-1 rounded" href="{{ path('list') }}">Voir la liste des événements</a>
    </section>

{% endblock %}

templates/event/list.html.twig
{% extends "base.html.twig" %}

{% block title %} {{ parent() }} - Liste{% endblock %}

{% block body %}

    <h2 class="text-center text-2xl font-semibold my-8 text-black">Evénements</h2>

    <section class="grid grid-cols-4 max-w-[1200px] mx-auto gap-8">
        {% for event in events %}
            <article class="drop-shadow-lg bg-white p-5 border">
                {% if event.image != '' %}
                    <img class="w-full h-[150px] object-cover" src="{{ event.image }}">
                {% endif %}
                <h3 class="font-semibold text-2xl mb-1 pb-1 border-b">{{ event.name }}</h3>
                <p class="text-sm text-gray-500 text-justify mb-5">{{ event.description }}</p>
                <p class="mb-5">
                    Du {{ event.releasedAt|date('d/m/Y') }} à {{ event.releasedAt|date('h') }}h{{ event.releasedAt|date('m') }} au {{ event.finishedAt|date('d/m/Y') }} à {{ event.finishedAt|date('h') }}h{{ event.finishedAt|date('m') }}
                </p>
                <div>
                    <a class="bg-blue-500 text-white px-2 py-1 duration-500 rounded hover:bg-blue-600" href="{{ path('show', { id: event.id }) }}">Voir</a>
                    <span>Tags</span>
                </div>
            </article>
        {% endfor %}
    </section>

{% endblock %}

templates/event/show.html.twig
{% extends "base.html.twig" %}

{% block title %}{{ parent() }} - Détails{% endblock %}

{% block body %}

    <h2 class="text-center text-2xl font-semibold my-8 text-black">Détails de l'événement <span class="font-semibold">{{ event.name }}</span></h2>

    <section class="max-w-[800px] mx-auto p-4 drop-shadow-lg border rounded">
        <h3 class="text-center font-semibold text-2xl mb-8 mt-3">{{ event.name }}</h3>
        {% if event.image != '' %}
            <img class="w-full object-cover my-3" src="{{ event.image }}">
        {% endif %}
        <article class="border-b mb-3">
            <h5 class="font-semibold mb-1">Description</h5>
            <p class="mb-3 text-justify pl-2">{{ event.description }}</p>
        </article>
        <article class="border-b mb-3">
            <h5 class="font-semibold mb-1">Date de début</h5>
            <p class="mb-3 text-justify pl-2">
                {{ event.releasedAt|date('d/m/Y') }} à {{ event.releasedAt|date('h') }}h{{ event.releasedAt|date('m') }}
            </p>
        </article>
        <article class="border-b mb-3">
            <h5 class="font-semibold mb-1">Date de fin</h5>
            <p class="mb-3 text-justify pl-2">
                {{ event.finishedAt|date('d/m/Y') }} à {{ event.finishedAt|date('h') }}h{{ event.finishedAt|date('m') }}
            </p>
        </article>
        <article class="border-b mb-3">
            <h5 class="font-semibold mb-1">Evénement créé le</h5>
            <p class="mb-3 text-justify pl-2">
                {{ event.createdAt|date('d/m/Y') }} à {{ event.createdAt|date('h') }}h{{ event.createdAt|date('m') }}
            </p>
        </article>
        <article class="flex justify-center">
            <a class="bg-blue-500 text-white px-2 py-1 duration-500 rounded hover:bg-blue-600" href="{{ path('join', { id: event.id }) }}">Rejoindre l'événèment</a>
        </article>
    </section>
    
{% endblock %}